languageCode = "en-us"
publishDir = "docs"
baseurl = "https://alyshahb.github.io/alyshahb/"
theme = "aerial"
title = "Alyshah B."

[params]
  name = "Alyshah B."
  about = "Training &nbsp;&bull;&nbsp; Technology &nbsp;&bull;&nbsp; Travel"
  copyright = "Alyshah B. | GitHub Pages | Google Domains | HTML5 UP | Hugo"
  #To disable the scrolling background, set bg_scroll to disable. To enable, leave bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

  [[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/alyshahb"
  
  [[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://www.instagram.com/alyshahb/"
  
  [[params.social]]
    medium = "LinkedIn"
    icon = "linkedin"
    link = "https://www.linkedin.com/in/alyshahb"

  [[params.social]]
    medium = "Twitter"
    icon = "twitter"
    link = "https://twitter.com/alyshahb"
